version: 2

models:
  - name: curated_large_report_data
    description: "Transformed data"
    columns:
      - name: "season_id"
        description: "Primary key for the table"
        tests:
          - unique
          - not_null
      - name: "season_type_id"
        description: "Season id to identofy the season"
        relationship:
          - to: season.season_type_id
      - name: "network_id"
        desctipion: "Network id to identify the network"
        relationship:
          - to: network.network_type_id
      - name: "year"
        description: "Year for which the data was collected"
      - name: "component_id"
        description: "Id of the component"
        relationship:
          - to: component.component_type_id
      - name: "hour"
        description: "Hour of the day for which the data was collected"
      - name: "value"
        description: "Data value"