version: 1

models:
  - name: large_data_curated
    description: "A curated data model with proper data for every column"
    columns:
      - name: _airbyte_large_report_hashid
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: "0-1 am"
        description: "Floating data value"
      - name: "6-7 pm"
        description: "Floating data value"
      - name: "7-8 am"
        description: "Floating data value"
      - name: "8-9 am"
        description: "Floating data value"
      - name: "12-1 pm"
        description: "Floating data value"
      - name: "4-5 pm"
        description: "Floating data value"
      - name: "2-3 am"
        description: "Floating data value"
      - name: "6-7 am"
        description: "Floating data value"
      - name: "7-8 pm"
        description: "Floating data value"
      - name: "10-11 pm"
        description: "Floating data value"
      - name: "1-2 am"
        description: "Floating data value"
      - name: "3-4 pm"
        description: "Floating data value"
      - name: "8-9 pm"
        description: "Floating data value"
      - name: "9-10 pm"
        description: "Floating data value"
      - name: "2-3 pm"
        description: "Floating data value"
      - name: "10-11 am"
        description: "Floating data value"
      - name: "1-2 pm"
        description: "Floating data value"
      - name: "5-6 am"
        description: "Floating data value"
      - name: "3-4 am"
        description: "Floating data value"
      - name: "9-10 am"
        description: "Floating data value"
      - name: "11 am-12 pm"
        description: "Floating data value"
      - name: "11 pm-12 am"
        description: "Floating data value"
      - name: "5-6 pm"
        description: "Floating data value"
      - name: "4-5 am"
        description: "Floating data value"
      - name: "year"
        description: "Integer denoting the year"
      - name: "network"
        description: "Provides the geographical location from where the data is collected"
      - name: "season"
        description: "Details about which season the data was collected"
      - name: "component"
        description: "Details component for which the data belongs"