version: 2

models:
  - name: networks
    description: "A unique list of networks"
    columns:
      - name: network_type_id
        description: "The primary key for this table"
        data_type: varchar
        tests:
          - unique
          - not_null
      - name: "network_type"
        data_type: varchar
        description: "Type of networks, eg: Winter, Summer"