version: 2

models:
  - name: seasons
    description: "A unique list of seasons"
    columns:
      - name: season_type_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: "season_type"
        description: "Type of season, eg: Winter, Summer"